name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # 이 단계에서 GitHub 저장소의 파일을 로컬 워크플로우 환경에 체크아웃합니다.

    - name: List files in workspace
      run: ls -alh
      # 워크플로우 환경에서 파일 목록을 나열합니다.

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
      # SSH 키를 설정하여 Lightsail 서버에 접근할 수 있게 합니다.

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_SSH_KEY }} -r * ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/var/www
      # GitHub 저장소의 파일을 Lightsail 서버의 지정된 디렉토리로 복사합니다.

    - name: Verify files on server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_SSH_KEY }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} 'ls -alh /var/www'
      # 서버에서 파일 목록을 나열하여 복사가 성공적으로 이루어졌는지 확인합니다.

    - name: Restart Apache service
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_SSH_KEY }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} 'sudo systemctl restart apache2'
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_SSH_KEY }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} 'sudo systemctl status apache2'
      # Apache 서비스를 재시작하고 상태를 확인하여 서비스가 정상적으로 작동하는지 확인합니다.
